function SaveImage(FrameType,cri,camera_name,frame,path,array_location_number,image_location_number,wavelength,cri_wavelength,exposure,slide_number)

%saving image
if cri
    if camera_name == 'Andor iXon'
        frametemp = uint8(255*double(frame) / 16628);
    end
    image_filepath = [path,'\',num2str(array_location_number),'\',...
        num2str(image_location_number),'\',num2str(wavelength),...
        '\',num2str(cri_wavelength),'\',FrameType];
    file_name = [num2str(exposure),'-',slide_number,'-',num2str(array_location_number),'-',...
        num2str(image_location_number),'-',num2str(wavelength),...
        '-',num2str(cri_wavelength),'-',FrameType,'.tif'];
else
    image_filepath = [path,'\',num2str(array_location_number),'\',...
        num2str(image_location_number),'\',num2str(wavelength),...
        '\',num2str(0),'\',FrameType];
    file_name = [num2str(exposure),'-',slide_number,'-',num2str(array_location_number),'-',...
        num2str(image_location_number),'-',num2str(wavelength),...
        '-',num2str(0),'-',FrameType,'.tif'];
end
if not(exist(image_filepath,'dir'))
    mkdir(image_filepath);
end
imwrite(frametemp,[image_filepath,'\',file_name]);